//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetfinal.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjetFinalECommerceEntities5 : DbContext
    {
        public ProjetFinalECommerceEntities5()
            : base("name=ProjetFinalECommerceEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Commande> Commandes { get; set; }
        public virtual DbSet<ligneCommande> ligneCommandes { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
    }
}
